apiVersion: v1
kind: ConfigMap
metadata:
  name: companies-app-config
  labels:
    app: companies-app
data:
  ENV: dev
  PORT: "3000"
  NAME: companies
  LOG_LEVEL: debug
  DB_HOST: companies-postgres
  DB_PORT: "5432"
  DB_USERNAME: user
  DB_PASSWORD: pass
  DB_NAME: companies
  DB_MIGRATION_DIR: internal/migrations
  DB_DIALECT: postgres