swagger: "2.0"
info:
  version: "1.0.0"
  title: "Companies"
basePath: "/v1"
tags:
  - name: "company"
    description: "Everything about companies"
schemes:
  - "https"
  - "http"
paths:
  /company:
    post:
      tags:
        - "company"
      summary: "Add a new company"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Company object"
          required: true
          schema:
            $ref: "#/definitions/Company"
      responses:
        "405":
          description: "Invalid input"
    put:
      tags:
        - "company"
      summary: "Update an existing company"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Company object that needs to be updated"
          required: true
          schema:
            $ref: "#/definitions/Company"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Company not found"
        "405":
          description: "Validation exception"

  /company/{companyId}:
    get:
      tags:
        - "company"
      summary: "Find company by ID"
      description: "Returns a single pet"
      operationId: "getPetById"
      produces:
        - "application/json"
      parameters:
        - name: "companyId"
          in: "path"
          description: "ID of company to return"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Company"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Company not found"

    delete:
      tags:
        - "company"
      summary: "Deletes a company"
      produces:
        - "application/json"
      parameters:
        - name: "companyId"
          in: "path"
          description: "Company id to delete"
          required: true
          type: "string"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Company not found"

definitions:
  Company:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      address:
        type: object
        properties:
          street:
            type: string
          postcode:
            type: string
          city:
            type: string
      industry:
        $ref: "#/definitions/Industry"
      created:
        type: number
        description: "UNIX timestamp"
  Industry:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      marketValue:
        type: number
      co2Footprint:
        type: string